import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Clienti {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey()

  @ColumnInfo(name:'contatto')
  final int contatto;

  String name;
  int nPrenotazioni;

  //Default constructor
  Clienti(this.contatto, this.name, this.nPrenotazioni);
} 

@Entity(
  tableName: 'prenotazioni',
  primaryKeys: ['telefono', 'data'],
  foreignKeys: [
    ForeignKey(childColumns: ['telefono'],
    parentColumns: ['contatto'],
    entity: Clienti)
  ]
)
class Prenotazioni {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.

  @ColumnInfo(name:'telefono')
  final int telefono;
  
  @ColumnInfo(name:'data')
  DateTime data;

  final int nPersone;

  //Default constructor
  Prenotazioni(this.telefono, this.data, this.nPersone);
}//Prenotazioni 



      